CREATE user IBC IDENTIFIED by IBC
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, dba to IBC;

-- 회원 정보 테이블
CREATE TABLE TBL_MEMBER(
    MNO NUMBER(10) PRIMARY KEY, — 회원 고유번호
    ID VARCHAR2(20) NOT NULL, — 회원 아이디
    PASSWORD VARCHAR2(20) NOT NULL, — 회원 비밀번호
    CLASSIFICATION CHAR(1) DEFAULT 'n', — 회원 구분
    NAME VARCHAR2(20) NOT NULL, — 회원 이름
    NICKNAME VARCHAR2(20) NOT NULL, — 회원 닉네임
    GENDER VARCHAR2(4) NOT NULL, — 회원 성별
    BIRTH VARCHAR2(30) NOT NULL, — 회원 생년월일
    EMAIL VARCHAR2(30) NOT NULL, — 회원 이메일
    PHONE VARCHAR2(30) NOT NULL, — 회원 전화번호
    REG_DATE DATE DEFAULT SYSDATE — 회원 가입 날짜
);

-- 회원 고유 번호의 시퀀스
CREATE SEQUENCE SEQ_MEMBER;

--학원정보테이블
CREATE TABLE TBL_InstitutionInfo(
    INO NUMBER(10,0), --학원고유번호
    INAME VARCHAR2(20) NOT NULL, --학원이름
    ILOGO VARCHAR2(20) NOT NULL, 
    IADDRESS VARCHAR2(50) NOT NULL, --학원주소
    IPHONENUM VARCHAR2(20) NOT NULL, --학원전화번호
    IINTRO VARCHAR2(200) NOT NULL, --학원소개
    IREGDATE DATE DEFAULT SYSDATE, --홈페이지에 등록한 날짜
    IEVALUATION VARCHAR2(20) NOT NULL, --학원평가(별점으로할 예쩡)
    IHOMEPAGE VARCHAR2(50) NOT NULL, -- 학원홈페이지주소
    IESTABLISHMENT VARCHAR(20) NOT NULL --학원설립날짜
);
--학원고유번호의 시퀀스
CREATE SEQUENCE SEQ_Institution_INFO;
--학원테이블추가컬럼
ALTER TABLE tbl_institutioninfo ADD ISUBJECT VARCHAR2(200) NOT NULL; -- 학원과목
ALTER TABLE tbl_institutioninfo ADD IAREA VARCHAR2(50) NOT NULL; -- 학원지역

--기본키 설정
ALTER TABLE tbl_institutioninfo ADD CONSTRAINT pk_institutioninfo PRIMARY KEY (ino);

-- 게시판 시퀀스
CREATE SEQUENCE SEQ_FREE_FORUM;
-- 게시판 테이블
CREATE TABLE TBL_FORUM(
  FNO NUMBER(10,0) PRIMARY KEY, --게시판 글 고유번호
  FTITLE VARCHAR2(200) NOT NULL, --게시판 글 제목
  FSORT NUMBER(10,0) NOT NULL --게시판 분류
  FCONTENT VARCHAR2(3000) NOT NULL, --게시판 글 내용
  FWRITER VARCHAR2(50) NOT NULL, --게시판 글 작성자
  FREGDATE DATE DEFAULT SYSDATE, -- 게시판 글 작성시간
  FLIKE NUMBER(5) DEFAULT 0 -- 게시판 공감 OR 좋아요
  FVIEWS NUMBER(10) DEFAULT 0 -- 게시판 조회수
);
alter table TBL_FORUM add FSHOW char DEFAULT 'Y';
ALTER TABLE TBL_FORUM 
ADD CONSTRAINT CHK_FORUM CHECK (FSHOW IN('Y','N'));
-- 게시판 댓글 시퀀스
CREATE SEQUENCE SEQ_FORUM_REPLY;
-- 게시판 댓글 테이블
CREATE TABLE TBL_FREPLY(
FRNO NUMBER(10,0) PRIMARY KEY, --게시판 댓글 고유번호
FNO NUMBER(10,0), -- 게시판 글 고유번호
FRCONTENT VARCHAR2(500) NOT NULL, --게시판 댓글 내용
FRWRITER VARCHAR2(50) NOT NULL, --게시판 댓글 작성자
FRREGDATE DATE DEFAULT SYSDATE, --게시판 댓글 작성시간
FRLIKE NUMBER(5) DEFAULT 0,  -- 게시판 댓글 좋아요
constraint FRM_REP_FK foreign key (FNO) references TBL_FORUM (FNO)
);
alter table TBL_FREPLY add FRSHOW char DEFAULT 'Y';
ALTER TABLE TBL_FREPLY 
ADD CONSTRAINT CHK_REPLY CHECK (FRSHOW IN('Y','N'));

--문의사항 게시판 테이블
CREATE TABLE TBL_FAQ(
   FNO NUMBER PRIMARY KEY, -- 게시글 번호
   ADMIN_ID VARCHAR2(20) NOT NULL, -- 관리자 아이디   
   QUESTION VARCHAR2(100) NOT NULL, -- 질문
   ANSWER VARCHAR2(2000) NOT NULL, -- 대답
   READCOUNT NUMBER DEFAULT 0, --조회수
   REGDATE DATE NOT NULL, -- 작성일
   UPDATEDATE DATE NOT NULL, -- 수정일
   DEL CHAR(1) -- 삭제여부
);

--문의사항 댓글 테이블
CREATE TABLE TBL_FAQREPLY(
    RNO NUMBER PRIMARY KEY, --댓글 번호
    FNO NUMBER NOT NULL REFERENCES TBL_FAQ(FNO), -- 게시판 번호
    FID VARCHAR2(20) NOT NULL, --회원 아이디    
    CONTENT VARCHAR2(20) NOT NULL, -- 내용
    REGDATE DATE NOT NULL, -- 작성일
    UPDATEDATE DATE NOT NULL, -- 수정일
	DEL CHAR(1) -- 삭제여부
);